# xScores Config/Data File.
Stats-Tag: '&bYour stats&7'
Kills-Tag: '&aKills&7:'
Deaths-Tag: '&aDeaths&7:'
Balance-Tag: '&aBalance&7:'
Streak-Tag: '&aStreak&7:'
CaveSpider-Tag: '&aCSpider&7:'
Creeper-Tag: '&aCreeper&7:'
Enderman-Tag: '&aEnderman&7:'
Skeleton-Tag: '&aSkeleton&7:'
Spider-Tag: '&aSpider&7:'
Zombie-Tag: '&aZombie&7:'
Other-Tag: '&aOther&7:'

Stats-File-Save-Time: 20