main: me.kreashenz.xscores.xScores
name: xScores
description: xScores
version: 1.6
authors: [kreashenz, stuntguy3000]
softdepend: [Vault]
commands:
  clearscores:
    description: Reset the scoreboards.
  kdr:
    description: Display your kdr.
  xboard:
    description: Enable/disable the xScore scoreboard.
  xscore:
    description: Reload/save xScore config.